# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '__first__'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailaccountfolder',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailconversation',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailconversationreference',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workspace.Workspace'),
            preserve_default=False,
        ),
    ]
